name: "SFTP mirror"
description: "mirror local dir to remote"
branding:
  icon: upload-cloud
  color: purple
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  server:
    description: "server"
    required: true
  port:
    description: "server port (default: 22)"
    required: false
    default: "22"
  user:
    description: "user"
    required: true
  password:
    description: "Private SSH key for user (include via secrets if possible)"
    required: true
  local:
    description: "Local path to sync (default: .)"
    required: false
    default: .
  remote:
    description: "Path on server (default: .)"
    required: false
    default: .
